project_id = "ytmhzpchuuufutemjuen"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.test-live-checkout]
verify_jwt = false

[functions.support-chat]
verify_jwt = false
